# Generated by Django 5.0.7 on 2024-08-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='temp_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
