# Generated by Django 5.0.7 on 2024-08-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_ticket_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='temp_field',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='time_created',
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
