# Generated by Django 5.0.7 on 2024-08-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_ticket_temp_field_remove_ticket_time_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userfollows',
            name='followed_user',
        ),
        migrations.RemoveField(
            model_name='userfollows',
            name='user',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
