# Generated by Django 5.0.7 on 2024-08-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_rename_user_review_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="author",
            new_name="user",
        ),
    ]
