# Generated by Django 5.0.7 on 2024-08-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="created_at",
        ),
    ]
