# Generated by Django 5.0.7 on 2024-08-12 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_remove_ticket_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
